# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'V1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

import sys
#from student import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

from PyQt5.QtWidgets import QAction
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPalette

class Ui_MainWindow1(object):
    def setup(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(974, 813)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon.fromTheme("ProfMate")
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_logo.sizePolicy().hasHeightForWidth())
        self.label_logo.setSizePolicy(sizePolicy)
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("image/macpicture.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setWordWrap(True)
        self.label_logo.setObjectName("label_logo")
        self.verticalLayout_4.addWidget(self.label_logo)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_lecture = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_lecture.sizePolicy().hasHeightForWidth())
        self.label_lecture.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_lecture.setFont(font)
        self.label_lecture.setObjectName("label_lecture")
        self.horizontalLayout.addWidget(self.label_lecture)
        self.comboBox_lecture = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_lecture.sizePolicy().hasHeightForWidth())
        self.comboBox_lecture.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.comboBox_lecture.setFont(font)
        self.comboBox_lecture.setObjectName("comboBox_lecture")
        self.comboBox_lecture.addItem("")
        self.comboBox_lecture.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_lecture)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_section = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_section.sizePolicy().hasHeightForWidth())
        self.label_section.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.label_section.setFont(font)
        self.label_section.setObjectName("label_section")
        self.horizontalLayout_2.addWidget(self.label_section)
        self.comboBox_section = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_section.sizePolicy().hasHeightForWidth())
        self.comboBox_section.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        self.comboBox_section.setFont(font)
        self.comboBox_section.setObjectName("comboBox_section")
        self.comboBox_section.addItem("")
        self.comboBox_section.addItem("")
        self.comboBox_section.addItem("")
        self.comboBox_section.addItem("")
        self.comboBox_section.addItem("")
        self.comboBox_section.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_section)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("image/test.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_attendance = QtWidgets.QLabel(self.centralwidget)
        self.label_attendance.setObjectName("label_attendance")
        self.horizontalLayout_6.addWidget(self.label_attendance)
        self.lineEdit_attendance = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_attendance.sizePolicy().hasHeightForWidth())
        self.lineEdit_attendance.setSizePolicy(sizePolicy)
        self.lineEdit_attendance.setObjectName("lineEdit_attendance")
        self.horizontalLayout_6.addWidget(self.lineEdit_attendance)
        spacerItem3 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.listWidget_attendance = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_attendance.sizePolicy().hasHeightForWidth())
        self.listWidget_attendance.setSizePolicy(sizePolicy)
        self.listWidget_attendance.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_attendance.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_attendance.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_attendance.setObjectName("listWidget_attendance")

        self.verticalLayout_2.addWidget(self.listWidget_attendance)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_attendancRate = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_attendancRate.setFont(font)
        self.label_attendancRate.setMouseTracking(True)
        self.label_attendancRate.setTextFormat(QtCore.Qt.AutoText)
        self.label_attendancRate.setObjectName("label_attendancRate")
        self.horizontalLayout_7.addWidget(self.label_attendancRate)
        self.statusBar_rate = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar_rate.sizePolicy().hasHeightForWidth())
        self.statusBar_rate.setSizePolicy(sizePolicy)
        self.statusBar_rate.setProperty("value", 24)
        self.statusBar_rate.setObjectName("statusBar_rate")
        self.horizontalLayout_7.addWidget(self.statusBar_rate)
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_absent = QtWidgets.QLabel(self.centralwidget)
        self.label_absent.setObjectName("label_absent")
        self.horizontalLayout_4.addWidget(self.label_absent)
        self.lineEdit_absent = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_absent.sizePolicy().hasHeightForWidth())
        self.lineEdit_absent.setSizePolicy(sizePolicy)
        self.lineEdit_absent.setFrame(True)
        self.lineEdit_absent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_absent.setObjectName("lineEdit_absent")
        self.horizontalLayout_4.addWidget(self.lineEdit_absent)
        spacerItem6 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.listWidget_absent = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_absent.sizePolicy().hasHeightForWidth())
        self.listWidget_absent.setSizePolicy(sizePolicy)
        self.listWidget_absent.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_absent.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_absent.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_absent.setObjectName("listWidget_absent")
        self.verticalLayout_3.addWidget(self.listWidget_absent)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.viewAttendance_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewAttendance_btn.sizePolicy().hasHeightForWidth())
        self.viewAttendance_btn.setSizePolicy(sizePolicy)
        self.viewAttendance_btn.setObjectName("viewAttendance_btn")
        self.horizontalLayout_5.addWidget(self.viewAttendance_btn)
        spacerItem7 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.capture_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capture_btn.sizePolicy().hasHeightForWidth())
        self.capture_btn.setSizePolicy(sizePolicy)
        self.capture_btn.setObjectName("capture_btn")
        self.horizontalLayout_5.addWidget(self.capture_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        spacerItem8 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_lecture.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Lecture :</span></p></body></html>"))
        self.comboBox_lecture.setItemText(0, _translate("MainWindow", "ENG 4A06"))
        self.comboBox_lecture.setItemText(1, _translate("MainWindow", "COMPENG 4TL4"))
        self.label_section.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Section :</span></p></body></html>"))
        self.comboBox_section.setItemText(0, _translate("MainWindow", "Section 1001"))
        self.comboBox_section.setItemText(1, _translate("MainWindow", "Section 1002"))
        self.comboBox_section.setItemText(2, _translate("MainWindow", "Section 1003"))
        self.comboBox_section.setItemText(3, _translate("MainWindow", "Section 1004"))
        self.comboBox_section.setItemText(4, _translate("MainWindow", "Section 1005"))
        self.comboBox_section.setItemText(5, _translate("MainWindow", "Section 1006"))
        self.label_attendance.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#0000ff;\">Attandance </span></p></body></html>"))
        self.label_attendancRate.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#ff0000;\">Attandance Rate:  </span></p></body></html>"))
        self.label_absent.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; color:#ff0000;\">Absent</span></p></body></html>"))
        self.viewAttendance_btn.setText(_translate("MainWindow", "view attendance"))
        self.capture_btn.setText(_translate("MainWindow", "Capture"))
        self.viewAttendance_btn.clicked.connect(self.viewAttendance_btn_clicked)

    def viewAttendance_btn_clicked(self):
        # total=0
        # show=0
        # absent=0
        self.display_show_up()
        self.display_absent()
        # total=100*show/absent
        # print("Percentage = "+total)
        # self.Percentage.setProperty("value",total)

    def display_show_up(self):
        # filename = QFileDialog.getOpenFileName()
        # show=0

        showList = []
        path = 'C:/capstone/studentpage/show_up.txt'
        # print(path)
        # This is how to read a file
        with open(path, "r") as f:
            for listitem in f:
                # content=listitem
                # listInfo.append(content)
                # show=show+1
                showList.append(listitem)
                # print(listitem)
            f.close()
            for x in range(len(showList)):
                print(showList[x])
        # rself.updateShowUp(listInfo)
    def display_absent(self):
        # absent=0
        # filename = QFileDialog.getOpenFileName()
        path = 'C:/capstone/studentpage/absent.txt'
        # print(path)
        # This is how to read a file
        with open(path, "r") as f:
            for listitem in f:
                # absent=absent+1
                print(listitem)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow1()
    ui.setup(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
